import type {PageDef,FieldDef} from './cmis-register-data';
export const siCodes={
 tx:Array.from({length:16},(_,i)=>`${i.toString(16).toUpperCase()}h：${i===0?'无均衡':i<=12?`${i} dB（参考 CTLE 目标）`:'Custom：需厂商编码表'}`),
 pre:Array.from({length:16},(_,i)=>`${i.toString(16).toUpperCase()}h：${i<=7?`${i/2} dB`:i<=10?'Reserved：不可作为标准配置':'Custom：需厂商编码表'}`),
 post:Array.from({length:16},(_,i)=>`${i.toString(16).toUpperCase()}h：${i<=7?`${i} dB`:i<=10?'Reserved：不可作为标准配置':'Custom：需厂商编码表'}`),
 amplitude:Array.from({length:16},(_,i)=>`${i.toString(16).toUpperCase()}h：${i<4?['100–400','300–600','400–800','600–1200'][i]+' mV P-P 区间':i===15?'Custom：需厂商幅度定义':'Reserved：不可作为标准配置'}`),
};
export function enrichFields(pages:PageDef[]){
 const add=(pageName:string,offset:number,fields:FieldDef[])=>{const page=pages.find(p=>p.page===pageName)!;const range=page.ranges.find(r=>offset>=r.start&&offset<=r.end)!;range.fields=(range.fields||[]).filter(f=>{const m=f.address.split(':')[1].match(/^(\d+)(?:[–-](\d+))?/);return !m||!(offset>=+m[1]&&offset<=+(m[2]||m[1]));}).concat(fields);};
 const field=(page:string,offset:number,bits:string,name:string,access:string,meaning:string,values:string[]|undefined,source:string):FieldDef=>({address:`${page}:${offset}`,bits,name,access,level:!name.startsWith('SCS1')&&/MemoryModel|SteppedConfigOnly|MciMaxSpeed|AutoCommissioning|ModuleState|InterruptDeasserted|LowPwrAllowRequestHW|LowPwrRequestSW|SoftwareReset|DPDeinit|AppSelCode|DataPathID|ExplicitControl|DPState|ConfigStatus|DPInitPending|OutputStatus|SCS0::ApplyDPInit|SFF8024Identifier|Vendor(Name|OUI|PN|Rev|SN)|DateCode|ModulePowerClass|MaxPower|CableAssemblyLinkLength|ConnectorType|MediaInterfaceTechnology|PageChecksum/.test(name)?'强制':'条件强制',meaning,values,note:`逐位核对 · ${source}`});
 const bitmap=(page:string,offset:number,name:string,access:string,off:string,on:string,source:string,context='Host')=>add(page,offset,Array.from({length:8},(_,j)=>{const bit=7-j;return field(page,offset,String(bit),`${name} · ${context} Lane ${bit+1}`,access,`Bit ${bit} 对应本 Bank 的 ${context} Lane ${bit+1}。`,[`0b：${off}`,`1b：${on}`],source);}));
 const packed=(page:string,start:number,width:number,name:string,access:string,values:string[],source:string,meaning:string)=>{for(let b=0;b<8*width/8;b++){const per=8/width;add(page,start+b,Array.from({length:per},(_,j)=>{const pos=per-1-j,lo=pos*width;return field(page,start+b,`${lo+width-1}–${lo}`,`${name} · Host Lane ${b*per+pos+1}`,access,meaning,values,source);}));}};

 const def=(p:string,o:number,b:string,n:string,a:string,m:string,v:string[]|undefined,src:string)=>field(p,o,b,n,a,m,v,src);
 const reserve=(p:string,o:number,b='7–0')=>({...field(p,o,b,'Reserved','RO','保留字段，不赋予功能含义。',undefined,'CMIS 5.3 对应字段表'),level:'Reserved' as const});
 add('Lower',2,[def('Lower',2,'7','MemoryModel','RO','0=Paged，1=Flat。',['0b：分页模型，支持基础 Page 00h–02h、10h–11h','1b：Flat，只支持 Page 00h'],'Table 8-5'),def('Lower',2,'6','SteppedConfigOnly','RO','与低两位 AutoCommissioning 联合解释。',['0b：两种 intervention-free 配置均支持','1b：基础分步配置；额外能力由 AutoCommissioning 指定'],'Table 8-5'),def('Lower',2,'5–2','MciMaxSpeed','RO','最高管理接口速度代码；I2C 与 SPI 使用不同表。',Array.from({length:16},(_,i)=>i.toString(16).toUpperCase()+'h：I2C '+(['≤400 kHz','≤1 MHz','≤3.4 MHz'][i]||'Reserved')+'；SPI '+([1,2,4,8,12,16,20,30,40,50][i]?'≤'+[1,2,4,8,12,16,20,30,40,50][i]+' MHz':'Reserved')),'Table 8-5'),def('Lower',2,'1–0','AutoCommissioning','RO','SteppedConfigOnly=0 时本字段不限制能力；=1 时 00 无额外自动配置，01 仅 regular，10 仅 hot，11 Reserved。',undefined,'Table 8-5')]);
 add('Lower',3,[reserve('Lower',3,'7–4'),def('Lower',3,'3–1','ModuleState','RO','模块当前状态；不是状态变化 Flag。',['000b：Reserved','001b：ModuleLowPwr','010b：ModulePwrUp','011b：ModuleReady','100b：ModulePwrDn','101b：ModuleFault','110b：Reserved','111b：Reserved'],'Tables 8-6 / 8-7'),def('Lower',3,'0','InterruptDeasserted','RO','中断输出状态，不具有读取清除语义。',['0b：中断已断言','1b：中断未断言（默认）'],'Table 8-6')]);
 for(let bank=0;bank<4;bank++){const o=4+bank;add('Lower',o,[reserve('Lower',o,'7–4'),...[3,2,1,0].map(bit=>def('Lower',o,String(bit),`FlagsSummaryBank${bank}Page${['11h','12h','14h','2Ch'][bit]}`,'RO','Summary 不是 Flag；读取不清除下层事件。',['0b：该 Bank / Page 没有置位 Flag','1b：该 Bank / Page 至少有一个 Flag 置位'],'Table 8-8'))]);}
 const globals=[['ModuleStateChanged','ModuleFirmwareError','DataPathFirmwareError','Reserved','Reserved','Reserved','CdbCmdComplete1','CdbCmdComplete2'],['TempMonHighAlarm','TempMonLowAlarm','TempMonHighWarning','TempMonLowWarning','VccMonHighAlarm','VccMonLowAlarm','VccMonHighWarning','VccMonLowWarning'],['Aux1MonHighAlarm','Aux1MonLowAlarm','Aux1MonHighWarning','Aux1MonLowWarning','Aux2MonHighAlarm','Aux2MonLowAlarm','Aux2MonHighWarning','Aux2MonLowWarning'],['Aux3MonHighAlarm','Aux3MonLowAlarm','Aux3MonHighWarning','Aux3MonLowWarning','CustomMonHighAlarm','CustomMonLowAlarm','CustomMonHighWarning','CustomMonLowWarning']];
 globals.forEach((names,i)=>{for(const mask of [false,true]){const o=(mask?31:8)+i;add('Lower',o,[...names].map((n,bit)=>n==='Reserved'?reserve('Lower',o,String(bit)):def('Lower',o,String(bit),n+(mask?'Mask':'Flag'),mask?'RW':'RO/COR',mask?`控制 Lower:${8+i} Bit ${bit} 的中断贡献；不清除 Flag。`:'事件 / 条件锁存；读取该字节清除，持续条件可再次置位。',mask?['0b：允许此 Flag 贡献中断','1b：屏蔽此 Flag 的中断贡献']:['0b：未锁存此事件 / 条件','1b：已锁存此事件 / 条件'],mask?'Table 8-12':'Table 8-9')).reverse());}});
 for(const o of [12,28,35])add('Lower',o,[reserve('Lower',o)]);
 for(const o of [13,29,30,36])add('Lower',o,[def('Lower',o,'7–0','Custom','厂商定义','CMIS 规定厂商区域边界；具体 Bit 语义和访问行为需厂商表。',undefined,'Tables 8-9 / 8-11 / 8-12')]);
 add('Lower',26,[def('Lower',26,'7','BankBroadcastEnable','RW','对 lane-banked 页的控制写执行跨已支持 Bank 广播；能力 01h:156.7。',['0b：关闭 Bank 广播','1b：启用 Bank 广播，控制写会影响所有已支持 Lane Bank'],'Table 8-11'),def('Lower',26,'6','LowPwrAllowRequestHW','RW','决定硬件请求是否参与 LowPwrS 求值。',['0b：忽略硬件低功耗请求','1b：允许硬件低功耗请求（默认）'],'Table 8-11'),def('Lower',26,'5','SquelchMethodSelect','RW','能力由 Page 01h Table 8-50 声明；按相关接口选择。',['0b：Tx Squelch 降低 OMA','1b：Tx Squelch 降低平均功率 Pav'],'Table 8-11'),def('Lower',26,'4','LowPwrRequestSW','RW','软件低功耗请求。',['0b：不请求低功耗','1b：请求保持 / 返回低功耗'],'Table 8-11'),def('Lower',26,'3','SoftwareReset','WO/SC','写 1 触发复位并自清除；不会只修改普通控制值。',['0b：不触发复位','1b：触发软件复位'],'Table 8-11'),def('Lower',26,'2–0','Custom','厂商定义','厂商定义的三位，不能标为 Reserved 或自行赋予功能。',undefined,'Table 8-11')]);
 add('Lower',27,[reserve('Lower',27,'7–4'),def('Lower',27,'3–0','MciSpeedConfiguration','RW','适用于 SPIMCI；配置下一次事务的 SPI 速度。',Array.from({length:16},(_,i)=>i.toString(16).toUpperCase()+'h：'+([1,2,4,8,12,16,20,30,40,50][i]?[1,2,4,8,12,16,20,30,40,50][i]+' MHz':'Reserved')),'Table 8-11')]);

 // Page 00h — Administrative Information. Hex is the transport display;
 // each field below keeps its actual ASCII / numeric / enum / bitmap semantics.
 add('00h',128,[def('00h',128,'7–0','SFF8024IdentifierCopy','RO','Lower:0 的精确副本；按 SFF-8024 Table 4-1 解释模块形态。',undefined,'Tables 8-26 / 8-27')]);
 const asciiBlock=(start:number,end:number,prefix:string,label:string,source:string)=>{for(let o=start;o<=end;o++)add('00h',o,[def('00h',o,'7–0',`${prefix}Byte${o-start+1}`,'RO',`${label}的第 ${o-start+1}/${end-start+1} 个 ASCII 字节。应与同一区域其他字节拼接后解码；20h 是右侧填充空格。`,undefined,source)]);};
 asciiBlock(129,144,'VendorName','VendorName','Table 8-28 / §8.3.2.1');
 for(let o=145;o<=147;o++)add('00h',o,[def('00h',o,'7–0',`VendorOUIByte${o-144}`,'RO',`IEEE Company ID 的第 ${o-144}/3 个八位组；按 24-bit OUI 显示，不按 ASCII。三字节全零表示未指定。`,undefined,'Table 8-28 / §8.3.2.2')]);
 asciiBlock(148,163,'VendorPN','VendorPN','Table 8-28 / §8.3.2.3');
 asciiBlock(164,165,'VendorRev','VendorRev','Table 8-28 / §8.3.2.4');
 asciiBlock(166,181,'VendorSN','VendorSN','Table 8-28 / §8.3.2.5');
 const dateParts=['Year tens','Year ones','Month tens','Month ones','Day tens','Day ones','Lot code 1','Lot code 2'];
 for(let o=182;o<=189;o++)add('00h',o,[def('00h',o,'7–0',`DateCode${dateParts[o-182].replaceAll(' ','')}`,'RO',`${dateParts[o-182]} 的 ASCII 字符。182–183=年份后两位（00 表示 2000），184–185=01–12 月，186–187=01–31 日，188–189=可选批次码。`,undefined,'Table 8-29')]);
 asciiBlock(190,199,'CLEICode','CLEICode','Table 8-30');
 add('00h',200,[def('00h',200,'7–5','ModulePowerClass','RO','形态相关功耗等级；主机应优先使用 00h:201 MaxPower 做功耗准入。',Array.from({length:8},(_,i)=>`${i.toString(2).padStart(3,'0')}b：Power Class ${i+1}`),'Table 8-31'),reserve('00h',200,'4–0')]);
 add('00h',201,[def('00h',201,'7–0','MaxPower','RO','最坏条件及寿命范围内的最大功耗，编码单位 0.25 W，并向上取整。主机可据此判断是否允许 High Power Mode。',undefined,'Table 8-31 / §6.3.2.4')]);
 add('00h',202,[def('00h',202,'7–6','LengthMultiplier','RO','与低六位相乘得到米制长度。',['00b：×0.1','01b：×1','10b：×10','11b：×100'],'Table 8-32'),def('00h',202,'5–0','BaseLength','RO','线缆长度基础值，单位为米并乘以高两位倍率；0 表示未定义，FFh 表示大于 6300 m。',undefined,'Table 8-32')]);
 add('00h',203,[def('00h',203,'7–0','ConnectorType','RO','媒体侧连接器类型；具体编码查 SFF-8024 Table 4-3。',undefined,'Table 8-33')]);
 const attenFreq=['5 GHz','7 GHz','12.9 GHz','25.8 GHz','53.125 GHz'];
 for(let o=204;o<=208;o++)add('00h',o,[def('00h',o,'7–0',`AttenuationAt${attenFreq[o-204].replace(/[^0-9]/g,'')}`,'RO',`铜缆在 ${attenFreq[o-204]} 的外部可测衰减，U8、1 dB/LSB；0 表示数据不可用。PCIe Application 使用协议注明的另一组对应频点。`,undefined,'Table 8-34')]);
 add('00h',209,[reserve('00h',209)]);
 add('00h',210,Array.from({length:8},(_,j)=>{const bit=7-j;return def('00h',210,String(bit),`MediaLaneUnsupportedLane${bit+1}`,'RO',`近端 Media Lane ${bit+1} 的支持声明；不具有输出 Disable 控制作用。`,['0b：该 Media Lane 受支持','1b：该 Media Lane 不受支持'],'Table 8-35');}));
 const farEnd=['Undefined / detachable media','a b c d e f g h','a a a a a a a a','a a a a e e e e','a b c d e e e e','a b c c e e e e','a a c d e e e e','a a c c e e e e','a a a a e f g h','a a a a e f g g','a a a a e e g h','a a a a e e g g','a a c c e e g g','a b c c e e g g','a a c d e e g g','a b c d e e g g','a a c c e f g g','a b c c e f g g','a a c d e f g g','a b c d e f g g','a a c c e e g h','a b c c e e g h','a a c d e e g h','a b c d e e g h','a a c c e f g h','a b c c e f g h','a a c d e f g h','16-lane connector breakout','Reserved','Reserved','Reserved','Custom'];
 add('00h',211,[reserve('00h',211,'7–5'),def('00h',211,'4–0','FarEndConfiguration','RO','固定线缆远端模块的 Lane 分组拓扑；字母相同表示同一远端模块。可分离介质模块应为 0。',farEnd.map((x,i)=>`${i.toString(16).toUpperCase().padStart(2,'0')}h：${x}`),'Tables 8-36–8-38')]);
 const technology=['850 nm VCSEL','1310 nm VCSEL','1550 nm VCSEL','1310 nm FP laser','1310 nm DFB laser','1550 nm DFB laser','1310 nm EML','1550 nm EML','Others','1490 nm DFB laser','Passive copper, unequalized','Passive copper, equalized','Near/far-end limiting active EQ','Far-end limiting active EQ','Near-end limiting active EQ','Linear active EQ（deprecated）','C-band tunable laser','L-band tunable laser','Near/far-end linear active EQ','Far-end linear active EQ','Near-end linear active EQ'];
 add('00h',212,[def('00h',212,'7–0','MediaInterfaceTechnology','RO','模块媒体侧物理器件或线缆技术分类；这是 CMIS 自身枚举。',[...technology.map((x,i)=>`${i.toString(16).toUpperCase().padStart(2,'0')}h：${x}`),'15h–FFh：Reserved'],'Tables 8-39 / 8-40')]);
 add('00h',213,[def('00h',213,'7','MciFlowControlDurationEncoding','RO','仅 SPIMCI：决定低七位按固定 dummy byte 参数还是按持续时间解释。',['0b：静态；dummy bytes N=2+低七位','1b：随速度变化；D=0.2 μs×低七位，再结合当前 SPI 速度计算 N'],'Table 8-41'),def('00h',213,'6–0','MciFlowControlDuration','RO','流控参数；其物理含义由 Bit 7 与 Lower:27 当前 SPI 速度共同决定。',undefined,'Table 8-41')]);
 for(let o=214;o<=220;o++)add('00h',o,[reserve('00h',o)]);
 add('00h',221,[def('00h',221,'7–0','CustomStaticInformation','厂商定义','计入 PageChecksum 的单字节厂商静态信息；CMIS 不定义内部 Bit。',undefined,'Table 8-26')]);
 add('00h',222,[def('00h',222,'7–0','PageChecksum','RO','Byte 128–221 算术和的低 8 bit。必须取得完整范围后才能验证。',undefined,'§8.3.11')]);
 for(let o=223;o<=255;o++)add('00h',o,[def('00h',o,'7–0',`CustomNonVolatileByte${o-222}`,'厂商定义','非易失厂商信息字节；复位及掉电后保留，不属于 00h:222 的校验覆盖。ASCII 预览只能作为观察，不能据此认定字段结构。',undefined,'§8.3.12')]);
 const laneFlags=[['DPStateChanged','Host'],['FailureTx','Media'],['LOSTx','Host'],['CDRLOLTx','Host'],['AdaptiveInputEqFailTx','Host'],['OpticalPowerHighAlarmTx','Media'],['OpticalPowerLowAlarmTx','Media'],['OpticalPowerHighWarningTx','Media'],['OpticalPowerLowWarningTx','Media'],['LaserBiasHighAlarmTx','Media'],['LaserBiasLowAlarmTx','Media'],['LaserBiasHighWarningTx','Media'],['LaserBiasLowWarningTx','Media'],['LOSRx','Media'],['CDRLOLRx','Media'],['OpticalPowerHighAlarmRx','Media'],['OpticalPowerLowAlarmRx','Media'],['OpticalPowerHighWarningRx','Media'],['OpticalPowerLowWarningRx','Media'],['OutputStatusChangedRx','Host']];
 laneFlags.forEach(([n,context],i)=>{bitmap('11h',134+i,n+'Flag','RO/COR','没有锁存该事件 / 条件','已锁存该事件 / 条件；读取字节清除',`Tables 8-86–8-88；Mask 10h:${213+i}`,context);bitmap('10h',213+i,n+'Mask','RW','允许对应 Flag 贡献中断','屏蔽对应 Flag 的中断贡献；不清除 Flag',`Table 8-81；Flag 11h:${134+i}`,context);});
 for(const [o,n,off,on,c] of [
 [128,'DPDeinit','请求初始化','请求去初始化','Host'],[129,'InputPolarityFlipTx','不翻转 Tx 输入极性','翻转 Tx 输入极性','Host'],[130,'OutputDisableTx','允许 Tx 输出；实际输出还受状态 / Squelch 控制','禁用 Tx 输出','Media'],[131,'AutoSquelchDisableTx','启用自动 Tx Squelch','禁用自动 Tx Squelch','Media'],[132,'OutputSquelchForceTx','不强制 Squelch','强制 Tx Squelch','Media'],[134,'AdaptiveInputEqFreezeTx','不冻结自适应均衡','冻结最后一次自适应值','Host'],[137,'OutputPolarityFlipRx','不翻转 Rx 输出极性','翻转 Rx 输出极性','Host'],[138,'OutputDisableRx','允许 Rx 输出；不代表信号已有效','禁用 Rx 输出','Host'],[139,'AutoSquelchDisableRx','启用自动 Rx Squelch','禁用自动 Rx Squelch','Host']
 ] as const)bitmap('10h',o,n,'RW',off,on,'CMIS Tables 8-68 / 8-69',c);
 packed('10h',135,2,'AdaptiveInputEqStoreTx','WO',['00b：Reserved','01b：保存到 Buffer 1','10b：保存到 Buffer 2','11b：Reserved'],'CMIS Table 8-69；01h:161[6:5]','写入触发存储；缓冲区数量必须已广告。');
 const scs=(page:string,shift:number,access:string,prefix:string)=>{
 bitmap(page,153+shift,prefix+'AdaptiveInputEqEnableTx',access,'关闭自适应；允许受支持的主机目标控制','启用自适应；忽略 HostControlledInputEqTargetTx','Tables 8-73 / 8-78 / 8-94；能力 01h:161.3');
 packed(page,154+shift,2,prefix+'AdaptiveInputEqRecallTx',access,['00b：不 Recall','01b：Recall Buffer 1','10b：Recall Buffer 2','11b：Reserved'],'Table 6-2；Tables 8-73 / 8-78 / 8-94；01h:161[6:5]','Store/Recall 可独立于 ExplicitControl 使用；ACS 表示已调用的缓冲区。');
 packed(page,156+shift,4,prefix+'HostControlledInputEqTargetTx',access,siCodes.tx,'Table 6-6；Tables 8-73 / 8-78 / 8-94；01h:161.2；01h:153[3:0]','EC=1 且自适应关闭时使用。目标不得超过模块广告范围。');
 bitmap(page,160+shift,prefix+'CDREnableTx',access,'CDR Bypass（必须支持 Bypass）','启用 CDR','Tables 8-73 / 8-78 / 8-94；01h:161[1:0]');
 bitmap(page,161+shift,prefix+'CDREnableRx',access,'CDR Bypass（必须支持 Bypass）','启用 CDR','Tables 8-74 / 8-79 / 8-95；01h:162[1:0]');
 packed(page,162+shift,4,prefix+'OutputEqPreCursorTargetRx',access,siCodes.pre,'Table 6-7；Tables 8-74 / 8-79 / 8-95；01h:162[4:3]','仅同时支持 Pre 和 Post 时使用本字段；若仅支持单一 Cursor，本字段被忽略。');
 packed(page,166+shift,4,prefix+'OutputEqPostCursorTargetRx',access,siCodes.post,'Table 6-7；Tables 8-74 / 8-79 / 8-95；01h:162[4:3]','支持 Post 时设置 Post；仅支持 Pre 时也用本字段并使用较大的编码范围。');
 packed(page,170+shift,4,prefix+'OutputAmplitudeTargetRx',access,siCodes.amplitude,'Table 6-8；Tables 8-74 / 8-79 / 8-95；01h:162.2；01h:153[7:4]','指定幅度区间，测量以无 Rx 输出均衡条件及相关标准测试点为基准。');
 };
 scs('10h',0,'RW','SCS0::');scs('10h',35,'RW','SCS1::');scs('11h',61,'RO','ACS::');
 for(const [page,start,prefix,access] of [['10h',145,'SCS0','RW'],['10h',180,'SCS1','RW'],['11h',206,'ACS','RO']] as const){for(let i=0;i<8;i++)add(page,start+i,[field(page,start+i,'7–4',`${prefix}::AppSelCodeLane${i+1}`,access,'0=未使用；1–15 为模块广告中的 AppSel 序号。',undefined,'Tables 8-71 / 8-72 / 8-77 / 8-93'),field(page,start+i,'3–1',`${prefix}::DataPathIDLane${i+1}`,access,'Data Path 最低本地 Host Lane 号减 1；AppSel=0 时忽略。',undefined,'Tables 8-71 / 8-72 / 8-77 / 8-93'),field(page,start+i,'0',`${prefix}::ExplicitControlLane${i+1}`,access,'仅对已使用 Lane 有效；Apply 后决定 SI 参数来源。',['0b：Application-dependent SI，由模块确定','1b：使用主机暂存 SI，仍须满足逐项能力声明'],'§6.2.3.2；Table 6-2；Table 8-71')]);}
 for(const [o,name] of [[143,'SCS0::ApplyDPInit'],[144,'SCS0::ApplyImmediate'],[176,'SCS0::ApplyImmediateTx'],[177,'SCS0::ApplyImmediateRx'],[178,'SCS1::ApplyDPInit'],[179,'SCS1::ApplyImmediate'],[211,'SCS1::ApplyImmediateTx'],[212,'SCS1::ApplyImmediateRx']] as const)bitmap('10h',o,name,'WO','不为该 Lane 触发命令','为该 Lane 触发命令；位图覆盖完整 Data Path','Tables 8-70 / 8-75 / 8-76 / 8-80；单字节 WRITE；核对状态与广告');
 bitmap('11h',132,'OutputStatusRx','RO','当前没有有效 Rx 输出','当前有有效 Rx 输出','Table 8-85','Host');bitmap('11h',133,'OutputStatusTx','RO','当前没有有效 Tx 输出','当前有有效 Tx 输出','Table 8-85','Media');bitmap('11h',235,'DPInitPending','RO','无待完成的 DPInit','活动配置尚待 DPInit 实施','§8.10.7');
 const states=['Reserved','DPDeactivated','DPInit','DPDeinit','DPActivated','DPTxTurnOn','DPTxTurnOff','DPInitialized'];
 packed('11h',128,4,'DPState','RO',Array.from({length:16},(_,i)=>`${i.toString(16).toUpperCase()}h：${states[i]||'Reserved'}`),'Table 8-84','同一 Data Path 的各关联 Host Lane 应报告相同状态。');
 const status=['Undefined','ConfigSuccess','ConfigRejected：通用拒绝','ConfigRejectedInvalidAppSel','ConfigRejectedInvalidDataPath','ConfigRejectedInvalidSI','ConfigRejectedLanesInUse：部分 Lane 未去初始化','ConfigRejectedPartialDataPath','Reserved','Reserved','Reserved','Reserved','ConfigInProgress','Custom reject D','Custom reject E','Custom reject F'];
 packed('11h',202,4,'ConfigStatus','RO',status.map((s,i)=>`${i.toString(16).toUpperCase()}h：${s}`),'Tables 8-90 / 8-91','最近配置命令结果，不是链路状态。');
 for(const [start,name,unit] of [[154,'OpticalPowerTx','U16×0.1 μW；能力 01h:160.1'],[170,'LaserBiasTx','U16×2 μA×广告倍率；能力 / 倍率 01h:160'],[186,'OpticalPowerRx','U16×0.1 μW；能力 01h:160.2；类型 01h:151.4']] as const){for(let i=0;i<16;i++)add('11h',start+i,[field('11h',start+i,'7–0',`${name} Media Lane ${Math.floor(i/2)+1} · ${i%2?'LSB':'MSB'}`,'RO',`完整样本在 11h:${start+2*Math.floor(i/2)}–${start+2*Math.floor(i/2)+1}；本字节为${i%2?'低':'高'}八位。${unit}；单字节不足以确定测量值。`,undefined,'Table 8-89')]);}
}
